"""remove a column

Revision ID: 6d72030d1ea4
Revises: 18cf47d034f1
Create Date: 2024-11-09 14:59:36.944400

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '6d72030d1ea4'
down_revision: Union[str, None] = '18cf47d034f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'occupied_volume')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('occupied_volume', mysql.FLOAT(), nullable=True))
    # ### end Alembic commands ###
