"""add a column

Revision ID: 8def11fdca50
Revises: 6d72030d1ea4
Create Date: 2024-11-09 14:59:59.588301

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8def11fdca50'
down_revision: Union[str, None] = '6d72030d1ea4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('occupied_volume', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'occupied_volume')
    # ### end Alembic commands ###
